Refactoring (#142)
* Migration to Typescript (#141)

* Add typescript support

* Remove useless vtl sources

* Update dependencies

* Fix gitignore

* Create .prettierrc

* Remove old implementations

* Improve vitest config

* Fix absolute path import for errors folder

* Update Literal.ts

* Improve getTokenType

* Fix Bindings type

* Fix Conditional visitor

* Fix InNotInVisitor

* Update dependencies

* Fix errrors

* Improve visitors

* Update interpretor.ts

* Delete jest.config.js

* Fix path issues

* Fix cast matrix

* Fix string function issues

* Concert test files to TS

* Fix hasNullArgs import issue

* Update vitest.config.ts

* Fix visitInNotInExpr

* Fix TS issues

* Downgrade to Typescript 4 for storybook

* Improve TS support

* Update dependencies

* Update Dataset type

* Fix cast issue with dates

* Temp disable arithmetic ds test before refactoring

* Fix TS issues

* Temp keep old storybook configuration

* Init new Storybook

* Update ci.yml

* Add @vitest/coverage-v8

* Update ci.yml

* Init dataset refactoring

* Feat: arithmetics for datasets

* Add first_value & last_value support

* Create processing-engine

* Improve aggr

* Separate in-memory and wasm tests

* Fix TS issues

* Update dependencies

* Finish aggr impl

* Fix aggr issue with useless ids

* Improve configuration

* Improve storybook UI

* Improve storybook

* Fix arithmetic issue with dataset column types

* Fix dataset aggr issue with empty group by

* Improve Storybook UI component

* Update stories

* Fix scalar bindings handling

* Improve storybook stories

* Fix buildVtlBindings function for null values

* Fix re-render issue in Storybook

* Update Storybook

* Fix configuration

* Update documentation

* Add doc deployment to CI

* Fix version to 1.0.0

* Fix mdx minor issues

* Fix doc issues

* Update doc dependencies

* Remove useless dependencies

* Update doc dependencies

* Update doc coverage

* Switch to VTL 2.1

* Update docs for VTL 2.1

* Update random operator support

* Update numeric.spec.ts

* Update ci.yml

* Add new 2.1 VTL operators to docs

* Fix docs

* Update numeric.stories.ts

* Update VTL tools

* Update docs configuration

* Update README.md

* Update yarn.lock

* Update ci.yml

* Update @making-sense/vtl-2-1-antlr-tools-ts

* Init case operator

* v1.0.0-rc1

* Fix dependency declarations

* v1.0.0-rc2

* Update tsconfig.json

* v1.0.0-rc3

* Update tsconfig.json

* Remove unused

* Fix release

* Update ci.yml

* Update ci.yml

* Update ci.yml

* v1.0.0-rc4

* Remove absolute paths

* v1.0.0-rc5

* Update dependencies

* Fix imports

* v1.0.0-rc6

* Update tsconfig.json

* v1.0.0-rc7

* Refine configuration

* v1.0.0-rc8

* Update version to 1.0.0

---------

Co-authored-by: Hadrien Kohl <hadrien.kohl@gmail.com>
Co-authored-by: Joseph Garrone <joseph.garrone.gj@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,93 +1,175 @@
-name: Trevas JS CI
-
-on: [push]
+name: Trevas TS CI
+on: [push, pull_request]
 
 jobs:
-  test-build:
-    name: Test & build
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 16
-      - run: yarn
-      # Build modules
-      - run: yarn build
-      # Build sonar reports
-      - run: yarn test --coverage
-      - name: Upload deploy artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: coverage
-          path: coverage/
+    test:
+        runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v4
+            - uses: actions/setup-node@v4
+              with:
+                  node-version: 22
+            - run: yarn
+            - run: yarn build
+            - run: yarn test --coverage
+            - name: Upload deploy artifact
+              uses: actions/upload-artifact@v4
+              with:
+                  name: coverage
+                  path: coverage/
 
-  sonarcloud:
-    runs-on: ubuntu-latest
-    needs: test-build
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Download coverage artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: coverage
-          path: coverage
-      - name: SonarCloud Scan
-        uses: sonarsource/sonarcloud-github-action@master
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+    sonarcloud:
+        runs-on: ubuntu-latest
+        needs: test
+        if: (github.repository == 'InseeFr/Trevas-TS' && (
+            github.event_name == 'push') || (
+            github.event_name == 'pull_request' &&
+            github.event.pull_request.head.repo.fork == false
+            ))
+        steps:
+            - uses: actions/checkout@v4
+              with:
+                  fetch-depth: 0
+            - name: Download coverage artifact
+              uses: actions/download-artifact@v4
+              with:
+                  name: coverage
+                  path: coverage
+            - name: SonarCloud Scan
+              uses: sonarsource/sonarcloud-github-action@master
+              env:
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-  build-assets:
-    if: github.ref == 'refs/heads/master'
-    runs-on: ubuntu-latest
-    needs: sonarcloud
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 16
-      - run: yarn
-      # Build modules
-      - run: yarn build
-      # Build Storybook
-      - run: yarn build-storybook
-      - run: mkdir -p deploy/storybook
-      - run: cp -R ./built-storybook/storybook/. ./deploy/storybook
-      # Build bundle reports
-      - run: yarn analyze
-      - run: mkdir -p deploy/bundle-report
-      - run: cp -a ./packages/vtl-2.0-antlr-tools/bundle-report/. ./deploy/bundle-report
-      - run: cp -a ./packages/trevas/bundle-report/. ./deploy/bundle-report
-      - uses: actions/setup-node@v3
-        with:
-          # Because of gitbook support
-          node-version: 10
-      - run: |
-          npm i -g gitbook-cli
-          gitbook install
-          gitbook build
-        working-directory: ./docs/
-      - run: cp -a ./docs/_book/. ./deploy/
-      - name: Upload deploy artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: deploy
-          path: deploy/
+    check_if_version_upgraded:
+        name: Check if version upgrade
+        # When someone forks the repo and opens a PR we want to enables the tests to be run (the previous jobs)
+        # but obviously only us should be allowed to release.
+        # In the following check we make sure that we own the branch this CI workflow is running on before continuing.
+        # Without this check, trying to release would fail anyway because only us have the correct secret.NPM_TOKEN but
+        # it's cleaner to stop the execution instead of letting the CI crash.
+        if: |
+            github.ref == 'refs/heads/master' && (
+            github.event_name == 'push' || 
+            github.event.pull_request.head.repo.owner.login == github.event.pull_request.base.repo.owner.login)
+        runs-on: ubuntu-latest
+        needs: sonarcloud
+        outputs:
+            from_version: ${{ steps.step1.outputs.from_version }}
+            to_version: ${{ steps.step1.outputs.to_version }}
+            is_upgraded_version: ${{ steps.step1.outputs.is_upgraded_version }}
+            is_pre_release: ${{steps.step1.outputs.is_pre_release }}
+        steps:
+            - uses: garronej/ts-ci@v2.1.5
+              id: step1
+              with:
+                  action_name: is_package_json_version_upgraded
+                  branch: ${{ github.head_ref || github.ref }}
 
-  deploy:
-    if: github.ref == 'refs/heads/master'
-    runs-on: ubuntu-latest
-    needs: build-assets
-    steps:
-      - name: Download deploy artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: deploy
-      - name: Deploy
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: .
+    create_github_release:
+        runs-on: ubuntu-latest
+        # We create release only if the version in the package.json have been upgraded and this CI is running against the main branch.
+        # We allow branches with a PR open on main to publish pre-release (x.y.z-rc.u) but not actual releases.
+        if: |
+            needs.check_if_version_upgraded.outputs.is_upgraded_version == 'true' &&
+            (
+              github.event_name == 'push' ||
+              needs.check_if_version_upgraded.outputs.is_pre_release == 'true'
+            )
+        needs:
+            - check_if_version_upgraded
+        steps:
+            - uses: softprops/action-gh-release@v2
+              with:
+                  name: Release v${{ needs.check_if_version_upgraded.outputs.to_version }}
+                  tag_name: v${{ needs.check_if_version_upgraded.outputs.to_version }}
+                  target_commitish: ${{ github.head_ref || github.ref }}
+                  generate_release_notes: true
+                  draft: false
+                  prerelease: ${{ needs.check_if_version_upgraded.outputs.is_pre_release == 'true' }}
+              env:
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+    publish_on_npm:
+        runs-on: ubuntu-latest
+        needs:
+            - create_github_release
+            - check_if_version_upgraded
+        steps:
+            - uses: actions/checkout@v4
+              with:
+                  ref: ${{ github.ref }}
+            - uses: actions/setup-node@v4
+              with:
+                  registry-url: https://registry.npmjs.org/
+            - uses: bahmutov/npm-install@v1
+            - run: npm run build
+            - run: npx -y -p denoify@1.6.16 enable_short_npm_import_path
+              env:
+                  DRY_RUN: "0"
+            - uses: garronej/ts-ci@v2.1.5
+              with:
+                  action_name: remove_dark_mode_specific_images_from_readme
+            - name: Publishing on NPM
+              run: |
+                  if [ "$(npm show . version)" = "$VERSION" ]; then
+                    echo "This version is already published"
+                    exit 0
+                  fi
+                  if [ "$NODE_AUTH_TOKEN" = "" ]; then
+                    echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
+                    false
+                  fi
+                  EXTRA_ARGS=""
+                  if [ "$IS_PRE_RELEASE" = "true" ]; then
+                      EXTRA_ARGS="--tag next"
+                  fi
+                  npm publish $EXTRA_ARGS
+              env:
+                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
+                  VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
+                  IS_PRE_RELEASE: ${{ needs.check_if_version_upgraded.outputs.is_pre_release }}
+
+    build-assets:
+        if: github.ref == 'refs/heads/master'
+        runs-on: ubuntu-latest
+        needs: sonarcloud
+        steps:
+            - uses: actions/checkout@v4
+            - uses: actions/setup-node@v4
+              with:
+                  node-version: 22
+            - run: yarn
+            # Build modules
+            - run: yarn build
+            # Build Storybook
+            - run: yarn build-storybook
+            - run: mkdir -p deploy/storybook
+            - run: cp -R ./storybook-static. ./deploy/storybook
+            # Build documentation
+            - run: |
+                  yarn install --frozen-lockfile
+                  yarn build
+              working-directory: ./docs/
+            - run: mkdir -p deploy/docs
+            - run: cp -R ./docs/build/. ./deploy/docs
+            - name: Upload deploy artifact
+              uses: actions/upload-artifact@v4
+              with:
+                  name: deploy
+                  path: deploy/
+
+    deploy:
+        if: github.ref == 'refs/heads/master'
+        runs-on: ubuntu-latest
+        needs: build-assets
+        steps:
+            - name: Download deploy artifact
+              uses: actions/download-artifact@v4
+              with:
+                  name: deploy
+            - name: Deploy
+              uses: peaceiris/actions-gh-pages@v4
+              with:
+                  github_token: ${{ secrets.GITHUB_TOKEN }}
+                  publish_dir: .
